#ifndef FTP_STATUS_H
#define FTP_STATUS_H

typedef enum
{
    COMM_INITIAL,
    COMM_SUCCESS,
    COMM_FAILED,
    LOGIN_INITIAL,
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    SEND_SUCCESS,
    SEND_FAILED,
    REV_SUCCESS,
    REV_FAILD,
} FTP_STATUS;

typedef enum
{
    COMM_INITIAL_TO_SUCCESS,
    COMM_INITIAL_TO_FAILED,
    SEND_FILE_TO_SUCCESS,
    SEND_FILE_TO_FAILED,
    LOGIN_TO_INITIAL,
    LOGIN_TO_SUCCESS,
    LOGIN_TO_FAILED,
    REV_FILE_TO_SUCCESS,
    REV_FILE_TO_FAILED,
    COMM_TO_RETRY,
    LOGIN_TO_RETRY,
} FTP_EVENT;

FTP_STATUS Ftp_GetStaus(void);
FTP_EVENT FTP_GetEvent(void);
void FTP_SetEvent(FTP_EVENT event);

#endif